genesis_unsupported = [
    "Dipole",
    "Sextupole",
    "Octupole",
    "Collimator",
    "Solenoid",
    "RFCavity",
    "RFDeflectingCavity",
    "Wakefield",
    "Aperture",
    "Wakefield",
    "Plasma",
    "TwissMatch",
    "ActivePlasmaLens",
    "CrabCavity",
]