wake_t_unsupported = [
    "Aperture",
    "Sextupole",
    "Octupole",
    "Decapole",
    "Solenoid",
    "Wakefield",
    "Wiggler",
    "Collimator",
    "Combined_Corrector",
    "Vertical_Corrector",
    "Horizontal_Corrector",
    "TwissMatch",
    "MatrixTransform",
    "CrabCavity",
]