from pybdsim.Builder import (
    Aperture,
    BLM,
    Drift,
    ECol,
    HKicker,
    Kicker,
    Laser,
    Marker,
    Multipole,
    Octupole,
    Quadrupole,
    Decapole,
    RBend,
    RCol,
    RFCavity,
    SBend,
    Sextupole,
    Solenoid,
    Undulator,
    VKicker,
    WireScanner,
    Rmat,
)

bdsim_conversion_rules = {
    "Dipole": SBend,
    "Solenoid": Solenoid,
    "Quadrupole": Quadrupole,
    "Sextupole": Sextupole,
    "Octupole": Octupole,
    "Decapole": Decapole,
    "Beam_Position_Monitor": Marker,
    "Beam_Arrival_Monitor": Drift,
    "Bunch_Length_Monitor": Drift,
    "Screen": Marker,
    "WireScanner": WireScanner,
    "Camera": Marker,
    "ChargeDiagnostic": Marker,
    "Photon_Monitor": Marker,
    "Collimator": ECol,
    "Monitor": Marker,
    "Wall_Current_Monitor": Drift,
    "Integrated_Current_Transformer": Drift,
    "Faraday_Cup_Monitor": Drift,
    "RFDeflectingCavity": Drift,
    "RFCavity": RFCavity,
    "Aperture": RCol,
    "Shutter": Drift,
    "Valve": Drift,
    "Bellows": Drift,
    "Cleaner": Drift,
    "Drift": Drift,
    "Scatter": Marker,
    "APContour": Marker,
    "FEL_Modulator": Undulator,
    "Wiggler": Undulator,
    "Wakefield": Marker,
    "Watch_Point": Marker,
    "Combined_Corrector": Kicker,
    "Horizontal_Corrector": HKicker,
    "Vertical_Corrector": VKicker,
    "Marker": Marker,
    "Laser": Laser,
    "Plasma": Drift,
    "Diagnostic": Marker,
    "TwissMatch": Marker,
    "MatrixTransform": Rmat,
    "RFMultipole": Multipole,
}
