from pybdsim.Builder import (
    Aperture,
    BLM,
    Drift,
    Ecol,
    Kicker,
    Laser,
    Marker,
    Octupole,
    Quadrupole,
    RBend,
    RCol,
    RFCavity,
    SBend,
    Sextupole,
    Solenoid,
    Undulator,
)

bdsim_conversion_rules = {
    "Dipole": SBend,
    "Solenoid": Solenoid,
    "Quadrupole": Quadrupole,
    "Sextupole": Sextupole,
    "Octupole": Octupole,
    "Beam_Position_Monitor": Marker,
    "Beam_Arrival_Monitor": Drift,
    "Bunch_Length_Monitor": Drift,
    "Screen": Marker,
    "Rcollimator": RCol,
    "Collimator": Ecol,
    "Monitor": Marker,
    "Wall_Current_Monitor": Drift,
    "Integrated_Current_Transformer": Drift,
    "Faraday_Cup_Monitor": Drift,
    "RFDeflectingCavity": RFCavity,
    "RFCavity": RFCavity,
    "Aperture": Aperture,
    "Shutter": Drift,
    "Valve": Drift,
    "Bellows": Drift,
    "Cleaner": Drift,
    "lscrift": Drift,
    "csrdrift": Drift,
    "edrift": Drift,
    "Drift": Drift,
    "Kicker": Kicker,
    "Scatter": Marker,
    "APContour": Marker,
    "Center": Marker,
    "FEL_Modulator": Undulator,
    "Wiggler": Undulator,
    "Charge": Marker,
    "Wakefield": Marker,
    "Watch_Point": Marker,
    "Combined_Corrector": Kicker,
    "Marker": Marker,
    "Laser": Laser,
    "Plasma": Drift,
    "Diagnostic": Marker,
    "TwissMatch": Marker,
}
