try:
    from cheetah.accelerator import (  # noqa: F401
        BPM,
        Aperture,
        Cavity,
        CombinedCorrector,
        CustomTransferMap,
        Dipole,
        Drift,
        Element,
        HorizontalCorrector,
        Marker,
        Quadrupole,
        RBend,
        Screen,
        Segment,
        Sextupole,
        Solenoid,
        SpaceChargeKick,
        TransverseDeflectingCavity,
        Undulator,
        VerticalCorrector,
    )
    _CHEETAH_AVAILABLE = True
except ImportError as _err:
    raise ImportError(
        "cheetah-accelerator is not installed. "
        "Install with: pip install \"laura-accelerator[cheetah]\""
    ) from _err

cheetah_conversion_rules = {
    "Dipole": Dipole,
    "Solenoid": Solenoid,
    "Quadrupole": Quadrupole,
    "Sextupole": Sextupole,
    "Octupole": Drift,
    "Decapole": Drift,
    "Beam_Position_Monitor": BPM,
    "Beam_Arrival_Monitor": Screen,
    "Bunch_Length_Monitor": Screen,
    "Screen": Screen,
    "RCollimator": Aperture,
    "Collimator": Aperture,
    "Monitor": Screen,
    "Wall_Current_Monitor": Drift,
    "Integrated_Current_Transformer": Drift,
    "Faraday_Cup_Monitor": Drift,
    "RFCavity": Cavity,
    "RFDeflectingCavity": TransverseDeflectingCavity,
    "CrabCavity": TransverseDeflectingCavity,
    "Aperture": Aperture,
    "Shutter": Drift,
    "Valve": Drift,
    "Bellows": Drift,
    "Cleaner": Drift,
    "lscdrift": Drift,
    "Drift": Drift,
    "csrdrift": Drift,
    "Kicker": CombinedCorrector,
    "Horizontal_Corrector": HorizontalCorrector,
    "Vertical_Corrector": VerticalCorrector,
    "Combined_Corrector": CombinedCorrector,
    "Marker": Screen,
    "Wakefield": Drift,
    "Laser": Drift,
    "Plasma": Drift,
    "Wiggler": Undulator,
    "Diagnostic": Screen,
    "Photon_Monitor": Screen,
    "TwissMatch": Marker,
    "MatrixTransform": CustomTransferMap,
}
