#!/usr/bin/env python3
"""
Propagate the PEP 8 renames into the hand-written Sphinx docs.

``docs/source/schema/`` is skipped: those ~496 files are generated by LinkML
from ``laura/schema/YAML``, whose class names were deliberately *not* renamed.

The hard part is that the same string can be a Python name or a data value, so
this rewrites only in contexts that are unambiguously Python:

* Sphinx cross-reference roles -- ``:py:class:`Quadrupole_Magnet <...>``` --
  which always denote Python objects;
* import lines inside code blocks;
* module paths, which pep8_rename.py never touches;
* a short allowlist of identifiers with no data meaning (``baseElement``,
  ``createDrifts``, ...).

Deliberately left alone:

* ``hardware_type`` values -- ``Beam_Position_Monitor`` in
  ``docs/source/Translator.rst``'s RF-Track table is a wire value, not a class;
* ``docs/source/Schema.rst``'s LinkML snippets, where ``Quadrupole_Magnet`` is
  the *schema* class, which still carries that name;
* ``.mex/patterns/pep8-rename-round.md``, which quotes legacy names as worked
  examples -- rewriting them makes its own gotchas read backwards.

    python tools/rename_docs.py --check | --apply
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from rename_modules import MODULE_RENAMES  # noqa: E402

#: Identifiers safe to rewrite anywhere in the docs: none is a hardware_type
#: value or a schema class name, so there is no data meaning to protect.
EXEMPT_FILES = {"pep8-rename-round.md"}

UNAMBIGUOUS: dict[str, str] = {
    "baseElement": "BaseElement",
    # round 5: importer/exporter entry points, used in docs in bare call form
    # (`read_YAML_Element_File(path)`) rather than in a role or import line.
    "read_YAML_Element_File": "read_yaml_element_file",
    "read_YAML_Element_Files": "read_yaml_element_files",
    "read_YAML_Combined_File": "read_yaml_combined_file",
    "interpret_YAML_Element": "interpret_yaml_element",
    "read_CATAP_YAML": "read_catap_yaml",
    "element_to_CATAP": "element_to_catap",
    "save_CATAP_file": "save_catap_file",
    "read_SimFrame_YAML": "read_simframe_yaml",
    "interpret_SimFrame_Element": "interpret_simframe_element",
    "get_SimFrame_YAML_filename": "get_simframe_yaml_filename",
    "get_SimFrame_MachineArea": "get_simframe_machine_area",
    "get_SimFrame_PV": "get_simframe_pv",
    "SimFrame_Conversion": "SimFrameConversion",
    "objectList": "ObjectList",
    "createDrifts": "create_drifts",
    "YAML_filename": "yaml_filename",
    "KToCurrent": "k_to_current",
    "KLToCurrent": "kl_to_current",
    "currentToK": "current_to_k",
    "currentToAngle": "current_to_angle",
    "checkValue": "check_value",
}

ROLE_RE = re.compile(
    r"(:(?:py:)?(?:class|func|meth|attr|obj|exc|data|mod):`)([^`]*)(`)"
)
IMPORT_RE = re.compile(r"^(\s*(?:from|import)\s+.*)$")


def load_identifier_map() -> dict[str, str]:
    merged: dict[str, str] = {}
    for f in sorted((ROOT / "tools/renames").glob("*.toml")):
        raw = tomllib.load(open(f, "rb"))
        for sec in ("classes", "functions", "globals"):
            merged.update(raw.get(sec, {}))
    return merged


def rewrite_roles(text: str, idmap: dict[str, str]) -> tuple[str, int]:
    """Rewrite the last dotted component of Sphinx role targets."""
    n = 0

    def sub(m: re.Match) -> str:
        nonlocal n
        head, body, tail = m.groups()
        # role bodies are either "Target" or "Label <dotted.Target>"
        def fix_dotted(dotted: str) -> str:
            nonlocal n
            for old, new in MODULE_RENAMES.items():
                if dotted.startswith(old + ".") or dotted == old:
                    dotted = new + dotted[len(old):]
                    n += 1
            parts = dotted.split(".")
            if parts[-1] in idmap:
                parts[-1] = idmap[parts[-1]]
                n += 1
            return ".".join(parts)

        angle = re.match(r"^(.*?)\s*<([^>]+)>$", body, re.DOTALL)
        if angle:
            label, target = angle.groups()
            new_target = fix_dotted(target)
            stripped = label.strip()
            new_label = fix_dotted(stripped) if "." in stripped else idmap.get(stripped, stripped)
            if new_label != stripped:
                n += 1
            if new_label == stripped and new_target == target:
                # Nothing changed -- return the original text untouched. Rebuilding
                # it would collapse a role wrapped across two lines onto one and
                # produce pure formatting churn.
                return m.group(0)
            return f"{head}{new_label} <{new_target}>{tail}"
        return f"{head}{fix_dotted(body.lstrip('~')) if '.' in body else idmap.get(body, body)}{tail}" \
            if "." in body or body in idmap else m.group(0)

    return ROLE_RE.sub(sub, text), n


def rewrite_file(path: Path, idmap: dict[str, str]) -> tuple[str, int]:
    if path.name in EXEMPT_FILES:
        return path.read_text(), 0
    text = original = path.read_text()
    total = 0

    text, n = rewrite_roles(text, idmap)
    total += n

    # module paths, everywhere (they have no data meaning)
    for old, new in MODULE_RENAMES.items():
        pat = rf"(?<![\w.]){re.escape(old)}(?![\w])"
        text, n = re.subn(pat, new, text)
        total += n

    lines = text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        # identifiers in import lines inside code blocks
        if IMPORT_RE.match(line) and "import" in line:
            for old, new in idmap.items():
                pat = rf"(?<![\w.]){re.escape(old)}(?![\w])"
                lines[i], n = re.subn(pat, new, lines[i])
                total += n
        # the unambiguous allowlist, anywhere
        for old, new in UNAMBIGUOUS.items():
            pat = rf"(?<![\w.]){re.escape(old)}(?![\w])"
            lines[i], n = re.subn(pat, new, lines[i])
            total += n
    text = "".join(lines)
    return text, (total if text != original else 0)


def main() -> int:
    ap = argparse.ArgumentParser()
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    idmap = load_identifier_map()
    files = [
        p for p in sorted((ROOT / "docs/source").rglob("*"))
        if p.suffix in {".rst", ".md"} and "schema" not in p.relative_to(ROOT / "docs/source").parts
    ]
    print(f"{len(files)} hand-written doc files ({len(idmap)} identifier renames)\n")

    total = 0
    for p in files:
        new_text, n = rewrite_file(p, idmap)
        if n:
            total += n
            print(f"  {p.relative_to(ROOT)}: {n}")
            if args.apply:
                p.write_text(new_text)
    print(f"\n{'applied' if args.apply else 'would apply'} {total} edits")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
